services:
  - type: web
    name: tiny-tyres
    runtime: static

    buildCommand: echo "Tiny Tyres static website"

    staticPublishPath: .

    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=3600

    routes:
      - type: rewrite
        source: /*
        destination: /index.html
